# Generated by Django 4.2.11 on 2024-04-09 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_teammembers_members_teammembers_members'),
        ('projects', '0001_initial'),
        ('tasks', '0002_alter_task_card_description_alter_task_card_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task_card',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='task_card',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AlterField(
            model_name='task_card',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task_card',
            name='due_date_reminder',
            field=models.CharField(choices=[('1', 'remind 1 days left'), ('2', 'remind 2 days left'), ('3', 'remind 3 days left')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='task_card',
            name='status',
            field=models.TextField(choices=[('0', 'notcompleted'), ('1', 'completed')], default='0', null=True),
        ),
        migrations.CreateModel(
            name='TaskCard_Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.FileField(upload_to='project_files')),
                ('task_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task_card')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teammembers')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
