# Generated by Django 4.2.11 on 2024-04-09 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_checklist_remove_task_card_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcard_attachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
