# Generated by Django 4.2.11 on 2024-04-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_teammember_role'),
        ('tasks', '0005_task_card_cover_task_card_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_member',
            name='member',
        ),
        migrations.AddField(
            model_name='task_checklist',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task_card'),
        ),
        migrations.AddField(
            model_name='task_member',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AlterField(
            model_name='task_card',
            name='cover',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task_card',
            name='status',
            field=models.TextField(choices=[('0', 'normal'), ('1', 'low'), ('2', 'high')], default='0', null=True),
        ),
    ]
