# Generated by Django 4.2.11 on 2024-04-09 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_teammember_role'),
        ('projects', '0002_project_team_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_member',
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
    ]
