# Generated by Django 4.2.11 on 2024-04-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_teammembers_teammember_team_teammember_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
