# Generated by Django 4.2.11 on 2024-06-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventsList',
        ),
    ]
